// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/order/contract.go
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/order/mocks/mock_repository.go -package=mocks -source=internal/modules/order/contract.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	core "go-fiber-pos/internal/core"
	order "go-fiber-pos/internal/modules/order"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// CreateWithTx mocks base method.
func (m *MockOrderRepository) CreateWithTx(tx *gorm.DB, arg1 *core.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithTx", tx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithTx indicates an expected call of CreateWithTx.
func (mr *MockOrderRepositoryMockRecorder) CreateWithTx(tx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithTx", reflect.TypeOf((*MockOrderRepository)(nil).CreateWithTx), tx, arg1)
}

// ExecuteTx mocks base method.
func (m *MockOrderRepository) ExecuteTx(fn func(*gorm.DB) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteTx", fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteTx indicates an expected call of ExecuteTx.
func (mr *MockOrderRepositoryMockRecorder) ExecuteTx(fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteTx", reflect.TypeOf((*MockOrderRepository)(nil).ExecuteTx), fn)
}

// FindByID mocks base method.
func (m *MockOrderRepository) FindByID(id uuid.UUID) (*core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockOrderRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockOrderRepository)(nil).FindByID), id)
}

// FindByIdempotencyKey mocks base method.
func (m *MockOrderRepository) FindByIdempotencyKey(key string) (*core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdempotencyKey", key)
	ret0, _ := ret[0].(*core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdempotencyKey indicates an expected call of FindByIdempotencyKey.
func (mr *MockOrderRepositoryMockRecorder) FindByIdempotencyKey(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdempotencyKey", reflect.TypeOf((*MockOrderRepository)(nil).FindByIdempotencyKey), key)
}

// FindVoucherByCode mocks base method.
func (m *MockOrderRepository) FindVoucherByCode(code string) (*core.Voucher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVoucherByCode", code)
	ret0, _ := ret[0].(*core.Voucher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindVoucherByCode indicates an expected call of FindVoucherByCode.
func (mr *MockOrderRepositoryMockRecorder) FindVoucherByCode(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVoucherByCode", reflect.TypeOf((*MockOrderRepository)(nil).FindVoucherByCode), code)
}

// GetAll mocks base method.
func (m *MockOrderRepository) GetAll() ([]core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll")
	ret0, _ := ret[0].([]core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockOrderRepositoryMockRecorder) GetAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockOrderRepository)(nil).GetAll))
}

// GetNextQueueNumber mocks base method.
func (m *MockOrderRepository) GetNextQueueNumber(tx *gorm.DB, source string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextQueueNumber", tx, source)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextQueueNumber indicates an expected call of GetNextQueueNumber.
func (mr *MockOrderRepositoryMockRecorder) GetNextQueueNumber(tx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextQueueNumber", reflect.TypeOf((*MockOrderRepository)(nil).GetNextQueueNumber), tx, source)
}

// GetStoreMarkupFee mocks base method.
func (m *MockOrderRepository) GetStoreMarkupFee() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStoreMarkupFee")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetStoreMarkupFee indicates an expected call of GetStoreMarkupFee.
func (mr *MockOrderRepositoryMockRecorder) GetStoreMarkupFee() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStoreMarkupFee", reflect.TypeOf((*MockOrderRepository)(nil).GetStoreMarkupFee))
}

// LockAndGetProduct mocks base method.
func (m *MockOrderRepository) LockAndGetProduct(tx *gorm.DB, productID uuid.UUID) (*core.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LockAndGetProduct", tx, productID)
	ret0, _ := ret[0].(*core.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LockAndGetProduct indicates an expected call of LockAndGetProduct.
func (mr *MockOrderRepositoryMockRecorder) LockAndGetProduct(tx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LockAndGetProduct", reflect.TypeOf((*MockOrderRepository)(nil).LockAndGetProduct), tx, productID)
}

// MockOrderService is a mock of OrderService interface.
type MockOrderService struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceMockRecorder
	isgomock struct{}
}

// MockOrderServiceMockRecorder is the mock recorder for MockOrderService.
type MockOrderServiceMockRecorder struct {
	mock *MockOrderService
}

// NewMockOrderService creates a new mock instance.
func NewMockOrderService(ctrl *gomock.Controller) *MockOrderService {
	mock := &MockOrderService{ctrl: ctrl}
	mock.recorder = &MockOrderServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderService) EXPECT() *MockOrderServiceMockRecorder {
	return m.recorder
}

// Checkout mocks base method.
func (m *MockOrderService) Checkout(req order.CheckoutRequest) (*core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", req)
	ret0, _ := ret[0].(*core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Checkout indicates an expected call of Checkout.
func (mr *MockOrderServiceMockRecorder) Checkout(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockOrderService)(nil).Checkout), req)
}

// GetAllOrders mocks base method.
func (m *MockOrderService) GetAllOrders() ([]core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders")
	ret0, _ := ret[0].([]core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderServiceMockRecorder) GetAllOrders() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderService)(nil).GetAllOrders))
}

// GetOrderByID mocks base method.
func (m *MockOrderService) GetOrderByID(id uuid.UUID) (*core.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByID", id)
	ret0, _ := ret[0].(*core.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByID indicates an expected call of GetOrderByID.
func (mr *MockOrderServiceMockRecorder) GetOrderByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByID", reflect.TypeOf((*MockOrderService)(nil).GetOrderByID), id)
}
