// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/inventory/contract.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	inventory "go-fiber-pos/internal/modules/inventory"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockInventoryService is a mock of InventoryService interface.
type MockInventoryService struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceMockRecorder
	isgomock struct{}
}

// MockInventoryServiceMockRecorder is the mock recorder for MockInventoryService.
type MockInventoryServiceMockRecorder struct {
	mock *MockInventoryService
}

// NewMockInventoryService creates a new mock instance.
func NewMockInventoryService(ctrl *gomock.Controller) *MockInventoryService {
	mock := &MockInventoryService{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService) EXPECT() *MockInventoryServiceMockRecorder {
	return m.recorder
}

// AdjustStock mocks base method.
func (m *MockInventoryService) AdjustStock(ctx context.Context, req inventory.AdjustStockRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdjustStock", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AdjustStock indicates an expected call of AdjustStock.
func (mr *MockInventoryServiceMockRecorder) AdjustStock(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdjustStock", reflect.TypeOf((*MockInventoryService)(nil).AdjustStock), ctx, req)
}

// CreateDefaultStock mocks base method.
func (m *MockInventoryService) CreateDefaultStock(ctx context.Context, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefaultStock", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDefaultStock indicates an expected call of CreateDefaultStock.
func (mr *MockInventoryServiceMockRecorder) CreateDefaultStock(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefaultStock", reflect.TypeOf((*MockInventoryService)(nil).CreateDefaultStock), ctx, productID)
}

// DeductStockWithTx mocks base method.
func (m *MockInventoryService) DeductStockWithTx(ctx context.Context, tx *gorm.DB, productID uuid.UUID, qty int, referenceType, referenceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeductStockWithTx", ctx, tx, productID, qty, referenceType, referenceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeductStockWithTx indicates an expected call of DeductStockWithTx.
func (mr *MockInventoryServiceMockRecorder) DeductStockWithTx(ctx, tx, productID, qty, referenceType, referenceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeductStockWithTx", reflect.TypeOf((*MockInventoryService)(nil).DeductStockWithTx), ctx, tx, productID, qty, referenceType, referenceID)
}

// GetMovements mocks base method.
func (m *MockInventoryService) GetMovements(ctx context.Context, productID uuid.UUID) ([]inventory.InventoryMovementResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovements", ctx, productID)
	ret0, _ := ret[0].([]inventory.InventoryMovementResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovements indicates an expected call of GetMovements.
func (mr *MockInventoryServiceMockRecorder) GetMovements(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovements", reflect.TypeOf((*MockInventoryService)(nil).GetMovements), ctx, productID)
}

// GetStockByProductID mocks base method.
func (m *MockInventoryService) GetStockByProductID(ctx context.Context, productID uuid.UUID) (*inventory.InventoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockByProductID", ctx, productID)
	ret0, _ := ret[0].(*inventory.InventoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockByProductID indicates an expected call of GetStockByProductID.
func (mr *MockInventoryServiceMockRecorder) GetStockByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockByProductID", reflect.TypeOf((*MockInventoryService)(nil).GetStockByProductID), ctx, productID)
}
