// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/inventory/contract.go
//
// Generated by this command:
//
//	mockgen -destination=internal/modules/inventory/mocks/mock_repository.go -package=mocks -source=internal/modules/inventory/contract.go InventoryRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	core "go-fiber-pos/internal/core"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
	isgomock struct{}
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// CreateDefault mocks base method.
func (m *MockInventoryRepository) CreateDefault(ctx context.Context, productID uuid.UUID) (*core.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDefault", ctx, productID)
	ret0, _ := ret[0].(*core.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDefault indicates an expected call of CreateDefault.
func (mr *MockInventoryRepositoryMockRecorder) CreateDefault(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDefault", reflect.TypeOf((*MockInventoryRepository)(nil).CreateDefault), ctx, productID)
}

// CreateMovementWithTx mocks base method.
func (m *MockInventoryRepository) CreateMovementWithTx(tx *gorm.DB, movement *core.InventoryMovement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovementWithTx", tx, movement)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMovementWithTx indicates an expected call of CreateMovementWithTx.
func (mr *MockInventoryRepositoryMockRecorder) CreateMovementWithTx(tx, movement any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovementWithTx", reflect.TypeOf((*MockInventoryRepository)(nil).CreateMovementWithTx), tx, movement)
}

// DB mocks base method.
func (m *MockInventoryRepository) DB() *gorm.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(*gorm.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockInventoryRepositoryMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockInventoryRepository)(nil).DB))
}

// FindByProductID mocks base method.
func (m *MockInventoryRepository) FindByProductID(ctx context.Context, productID uuid.UUID) (*core.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductID", ctx, productID)
	ret0, _ := ret[0].(*core.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProductID indicates an expected call of FindByProductID.
func (mr *MockInventoryRepositoryMockRecorder) FindByProductID(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductID", reflect.TypeOf((*MockInventoryRepository)(nil).FindByProductID), ctx, productID)
}

// FindByProductIDForUpdateWithTx mocks base method.
func (m *MockInventoryRepository) FindByProductIDForUpdateWithTx(tx *gorm.DB, productID uuid.UUID) (*core.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProductIDForUpdateWithTx", tx, productID)
	ret0, _ := ret[0].(*core.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProductIDForUpdateWithTx indicates an expected call of FindByProductIDForUpdateWithTx.
func (mr *MockInventoryRepositoryMockRecorder) FindByProductIDForUpdateWithTx(tx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProductIDForUpdateWithTx", reflect.TypeOf((*MockInventoryRepository)(nil).FindByProductIDForUpdateWithTx), tx, productID)
}

// GetMovements mocks base method.
func (m *MockInventoryRepository) GetMovements(ctx context.Context, inventoryID uuid.UUID) ([]core.InventoryMovement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovements", ctx, inventoryID)
	ret0, _ := ret[0].([]core.InventoryMovement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovements indicates an expected call of GetMovements.
func (mr *MockInventoryRepositoryMockRecorder) GetMovements(ctx, inventoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovements", reflect.TypeOf((*MockInventoryRepository)(nil).GetMovements), ctx, inventoryID)
}

// UpdateWithTx mocks base method.
func (m *MockInventoryRepository) UpdateWithTx(tx *gorm.DB, inv *core.Inventory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithTx", tx, inv)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWithTx indicates an expected call of UpdateWithTx.
func (mr *MockInventoryRepositoryMockRecorder) UpdateWithTx(tx, inv any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithTx", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateWithTx), tx, inv)
}


